"use strict";

module.exports = {
    UNCLEAR: "?",
    OPENBAAR_VERVOER: "Openbaar Vervoer",
    HUUR_HUIS: "Huur Huis",
    INTERNET: "XS4All Internet",
    MOBIEL: "Mobiel abonnement",
    AUTOVERZEKERING: "Autoverzekering",
    ETEN_VERS: "Vers eten",
    ETEN_WERK: "Eten op werk",
    SUPERMARKT: "Supermarkt",
    UIT_ETEN: "Uiteten",
    TANKEN: "Tanken",
    PARKEREN: "Parkeren",
    DROGIST: "Drogist",
    APOTHEEK: "Apotheek",
    UITJES: "Uitjes",
    ALIEXPRESS: "AliExpress",
    BABY: "Baby",
    KLEDING: "Kleding",
    OVERBOEKING_FAMILIE: "Overboeking Familie",
    OVERBOEKING_INTERN: "Overboeking intern",
    ZORGVERZEKERING: "Zorgverzekering",
    REISVERZEKERING: "Zorgverzekering",
    SPORT: "Sport",
    BELASTING_GEMEENTE: "Gemeentebelasting",
    OPVANG: "Kinderopvang",
    ENERGIE: "Energie",
    WATER: "Water",
    WEGENBELASTING: "Wegenbelasting",
    WASSTRAAT: "Wasstraat",
    KAT: "Kat",
    VAKANTIE: "Vakantie",
    KAPPER: "Kapper",
    HUIS: "Huis",
    HOBBY: "Hobby",
    CADEAU: "Cadeau",
    SALARIS: "Salaris",
    WERK: "Werk",
    BELASTINGDIENST: "Belastingdienst",
    TANDARTS: "Tandarts",
    AUTO: "Auto",

    UNKNOWN: "Onbekend",
};
